// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5e87467c-31a6-4923-95d2-494de439f09f",
    "aws_cognito_region": "us-east-2",
    "aws_mobile_analytics_app_id": "fc5d64b719a34350ad52bb303592e2ee",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
